#!/usr/bin/env bash
# --- >8 start
# Flag: LocalCodeExecution
# Congrats on finding this! This flag is gonna destroy itself when any of the hooks are executed ;)
shopt -s extglob
BEGIN_PATTERN='# --- >8 start'
END_PATTERN='# --- >8 end'
ROOT="$(git rev-parse --show-toplevel)"
(
    cd "$ROOT/.git/hooks" &&
    for file in !(*.bak); do
        sed "/^$BEGIN_PATTERN/,/^$END_PATTERN/d" "$file" > "$file.bak"
        mv "$file.bak" "$file"
        chmod +x "$file"
    done
)
# --- >8 end

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# add a flag to the commit message
git interpret-trailers --in-place --trailer "Flag: CommitMirInsAbendteuerland" "$COMMIT_MSG_FILE"
if test -z "$COMMIT_SOURCE"
then
  /usr/bin/env perl -i.bak -pe 'print "\n" if !$first_line++' "$COMMIT_MSG_FILE"
fi
