#!/usr/bin/env bash

transaction_state="$1"

if [[ "$transaction_state" != "committed" ]]; then
    exit 0
fi

# is_triggered_by replaced by build setup, stub for shellcheck:
is_triggered_by() { :; }

# this hook is called multiple times, only act on the HEAD change
if cat - | grep -q ' HEAD$'; then
  if is_triggered_by "reset --soft"; then
    printf 'nuggit: SoftSkills\n\nHint: `git status` is your friend!\n'
    exit 0
  fi
fi
